FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=mmocoin/mmocoin
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY mmocoin.tar.gz /mmocoin.tar.gz
RUN tar -xvf /mmocoin.tar.gz

#ADD . /mmocoin
RUN cd /mmocoin/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /mmocoin && scripts/windows-crosscompile/compile-mmocoin.sh
